// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Table("compnayJobProfiles")]
    [Index("CompanyId", Name = "IX_compnayJobProfiles_CompanyId")]
    [Index("JobProfileId", Name = "IX_compnayJobProfiles_JobProfileId")]
    public partial class CompnayJobProfile
    {
        [Key]
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int JobProfileId { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("CompnayJobProfiles")]
        public virtual Company Company { get; set; }
        [ForeignKey("JobProfileId")]
        [InverseProperty("CompnayJobProfiles")]
        public virtual JobProfile JobProfile { get; set; }
    }
}