// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    public partial class Company
    {
        public Company()
        {
            CompnayJobProfiles = new HashSet<CompnayJobProfile>();
            StudentCompanies = new HashSet<StudentCompany>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string CompanyName { get; set; }
        [Required]
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }

        [InverseProperty("Company")]
        public virtual ICollection<CompnayJobProfile> CompnayJobProfiles { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<StudentCompany> StudentCompanies { get; set; }
    }
}