// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("Criteria", Name = "IX_DeptCriteria_Criteria")]
    [Index("DeptId", Name = "IX_DeptCriteria_DeptId")]
    public partial class DeptCriterion
    {
        public DeptCriterion()
        {
            InterviewResults = new HashSet<InterviewResult>();
        }

        [Key]
        public int Id { get; set; }
        public int Mark { get; set; }
        public int DeptId { get; set; }
        public int Criteria { get; set; }

        [ForeignKey("Criteria")]
        [InverseProperty("DeptCriteria")]
        public virtual InterviewCriterion CriteriaNavigation { get; set; }
        [ForeignKey("DeptId")]
        [InverseProperty("DeptCriteria")]
        public virtual InterviewDept Dept { get; set; }
        [InverseProperty("DeptCriteria")]
        public virtual ICollection<InterviewResult> InterviewResults { get; set; }
    }
}