// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("ExamId", Name = "IX_ExamQuestions_ExamId")]
    [Index("QuestionId", Name = "IX_ExamQuestions_QuestionId")]
    public partial class ExamQuestion
    {
        public ExamQuestion()
        {
            StudentAnswers = new HashSet<StudentAnswer>();
        }

        [Key]
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int ExamId { get; set; }
        public int Mark { get; set; }

        [ForeignKey("ExamId")]
        [InverseProperty("ExamQuestions")]
        public virtual Exam Exam { get; set; }
        [ForeignKey("QuestionId")]
        [InverseProperty("ExamQuestions")]
        public virtual Question Question { get; set; }
        [InverseProperty("ExamQuestionNavigation")]
        public virtual ICollection<StudentAnswer> StudentAnswers { get; set; }
    }
}