// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("ProgramId", Name = "IX_GraduatedIntakes_ProgramId")]
    public partial class GraduatedIntake
    {
        public GraduatedIntake()
        {
            GraduatedDepartments = new HashSet<GraduatedDepartment>();
            GraduatedStudents = new HashSet<GraduatedStudent>();
        }

        [Key]
        public int Id { get; set; }
        public string IntakeName { get; set; }
        public DateTime GraduationDate { get; set; }
        public int ProgramId { get; set; }

        [ForeignKey("ProgramId")]
        [InverseProperty("GraduatedIntakes")]
        public virtual Itiprogram Program { get; set; }
        [InverseProperty("Intake")]
        public virtual ICollection<GraduatedDepartment> GraduatedDepartments { get; set; }
        [InverseProperty("Intake")]
        public virtual ICollection<GraduatedStudent> GraduatedStudents { get; set; }
    }
}