// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Table("graduatedDepartments")]
    [Index("IntakeId", Name = "IX_graduatedDepartments_IntakeId")]
    public partial class GraduatedDepartment
    {
        public GraduatedDepartment()
        {
            GraduatedStudents = new HashSet<GraduatedStudent>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public int IntakeId { get; set; }

        [ForeignKey("IntakeId")]
        [InverseProperty("GraduatedDepartments")]
        public virtual GraduatedIntake Intake { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<GraduatedStudent> GraduatedStudents { get; set; }
    }
}