// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("ProgramId", Name = "IX_Intakes_ProgramId")]
    public partial class Intake
    {
        public Intake()
        {
            Departments = new HashSet<Department>();
        }

        [Key]
        public int Id { get; set; }
        public string IntakeName { get; set; }
        public int IntakeNum { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int ProgramId { get; set; }

        [ForeignKey("ProgramId")]
        [InverseProperty("Intakes")]
        public virtual Itiprogram Program { get; set; }
        [InverseProperty("Intake")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}