// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Table("ITIPrograms")]
    public partial class Itiprogram
    {
        public Itiprogram()
        {
            GraduatedIntakes = new HashSet<GraduatedIntake>();
            Intakes = new HashSet<Intake>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        [InverseProperty("Program")]
        public virtual ICollection<GraduatedIntake> GraduatedIntakes { get; set; }
        [InverseProperty("Program")]
        public virtual ICollection<Intake> Intakes { get; set; }
    }
}