// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    public partial class JobProfile
    {
        public JobProfile()
        {
            CompnayJobProfiles = new HashSet<CompnayJobProfile>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Descriptions { get; set; }

        [InverseProperty("JobProfile")]
        public virtual ICollection<CompnayJobProfile> CompnayJobProfiles { get; set; }
    }
}