// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("To", Name = "IX_Messages_To")]
    public partial class Message
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        [Column("CC")]
        public string Cc { get; set; }
        public int To { get; set; }

        [ForeignKey("To")]
        [InverseProperty("Messages")]
        public virtual Department ToNavigation { get; set; }
    }
}