// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("SubjectId", Name = "IX_Questions_SubjectId")]
    public partial class Question
    {
        public Question()
        {
            ExamQuestions = new HashSet<ExamQuestion>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [Column("header")]
        public string Header { get; set; }
        [Required]
        public string Body { get; set; }
        [Required]
        public string A { get; set; }
        [Required]
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        [Required]
        public string ModelAnswer { get; set; }
        public int SubjectId { get; set; }

        [ForeignKey("SubjectId")]
        [InverseProperty("Questions")]
        public virtual Subject Subject { get; set; }
        [InverseProperty("Question")]
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
    }
}