// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("CompanyId", Name = "IX_StudentCompanies_CompanyId")]
    [Index("GraduatedStudentsId", Name = "IX_StudentCompanies_GraduatedStudentsId")]
    public partial class StudentCompany
    {
        [Key]
        public int Id { get; set; }
        public int GraduatedId { get; set; }
        public int CompanyId { get; set; }
        public string Profile { get; set; }
        public string Notes { get; set; }
        public DateTime From { get; set; }
        public int? GraduatedStudentsId { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("StudentCompanies")]
        public virtual Company Company { get; set; }
        [ForeignKey("GraduatedStudentsId")]
        [InverseProperty("StudentCompanies")]
        public virtual GraduatedStudent GraduatedStudents { get; set; }
    }
}