// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("ExamId", Name = "IX_StudentExams_ExamId")]
    [Index("StudentId", Name = "IX_StudentExams_StudentId")]
    public partial class StudentExam
    {
        [Key]
        public int Id { get; set; }
        public int ExamId { get; set; }
        public int StudentId { get; set; }
        public int TotalDegree { get; set; }

        [ForeignKey("ExamId")]
        [InverseProperty("StudentExams")]
        public virtual Exam Exam { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("StudentExams")]
        public virtual Student Student { get; set; }
    }
}