// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StatefulProject
{
    [Index("ExamQuestion", Name = "IX_StudentAnswers_ExamQuestion")]
    [Index("StudentId", Name = "IX_StudentAnswers_StudentId")]
    public partial class StudentAnswer
    {
        [Key]
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int ExamQuestion { get; set; }
        public int Mark { get; set; }
        [Column("StudentMAnswer")]
        public string StudentManswer { get; set; }

        [ForeignKey("ExamQuestion")]
        [InverseProperty("StudentAnswers")]
        public virtual ExamQuestion ExamQuestionNavigation { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("StudentAnswers")]
        public virtual Student Student { get; set; }
    }
}